- module: elasticsearch
  xpack.enabled: true
  period: 10s
  hosts: ["https://es01:9200"]
  username: "elastic"
  password: "123456"
  ssl.enabled: true
  ssl.certificate_authorities: ["certs/ca/ca.crt"]

