metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false


output.logstash:
  hosts: ["logstash:5044"]
  loadbalance: true
  index: metricbeat




#output.elasticsearch:
  #hosts: ["https://es01:9200"] ## Monitoring cluster
  ## Optional protocol and basic auth credentials.
  #protocol: "https"
  #username: "elastic"
  #password: "123456"
  #ssl.enabled: true
  #ssl.certificate_authorities: ["certs/ca/ca.crt"]
