metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

# https://www.elastic.co/guide/en/beats/metricbeat/8.15/metricbeat-modules.html
metricbeat.modules:
  - module: docker
    metricsets:
      - "container"
      - "cpu"
      - "diskio"
      - "healthcheck"
      - "info"
      - "image"
      - "memory"
      - "network"
    hosts: ["unix:///var/run/docker.sock"]
    period: 10s
    enabled: true
  - module: elasticsearch
    metricsets:
      - node
      - node_stats
      #- index
      #- index_recovery
      #- index_summary
      #- ingest_pipeline
      #- shard
      #- ml_job
    period: 10s
    hosts: ["https://es01:9200"]
    username: "elastic"
    password: "123456"
    ssl.certificate_authorities: ["certs/ca/ca.crt"]
  - module: logstash
    metricsets: ["node", "node_stats"]
    enabled: true
    period: 10s
    hosts: ["logstash:9600"]



processors:
  - add_cloud_metadata: ~


output.logstash:
  hosts: ["logstash:5044"]
  loadbalance: true
  index: metricbeat




  #ou#tput.elasticsearch:
  #hosts: ["https://es01:9200"] ## Monitoring cluster
  #protocol: "https"
  #username: "elastic"
  #password: "123456"
  #ssl:
  #enabled: true
  #ca_trusted_fingerprint: "2E2183D75B89EB9D5EFFF8B40F158CA2267C9ED978849AE924A0C6DD8A05C8C5"
  #ssl.enabled: true
  #ssl.certificate_authorities: ["certs/ca/ca.crt"]
