FROM docker.elastic.co/elasticsearch/elasticsearch:8.15.2

MAINTAINER abs2free
RUN sh -c '/bin/echo -e "y" | /usr/share/elasticsearch/bin/elasticsearch-plugin install http://get.infini.cloud/elasticsearch/analysis-ik/8.15.2'
