services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"  # 将容器的 80 端口映射到主机的 80 端口
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx  # 将主机的 logs 目录挂载到容器的日志目录
